In [2]:
import polyscope as ps
import numpy as np
ps.init()


### Entendendo - Polyscope

Vamos primeiro definir três vértices para montarmos uma face triangular

Sendo os pontos $v1 = [1, 0, 0]$, $v2 = [0, 1, 0]$, $v3 = [0, 0, 1]$

$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$

In [3]:
import polyscope as ps
import numpy as np

ps.reset_camera_to_home_view()

# Definição dos vértices
vertices = np.array([
  [1.,0.,0.],
  [0.,1.,0.],
  [0.,0.,1.]
])

# Definição das faces
"""
Cada face é dada por um array de indices
No caso [[0,1,2]] temos que existe uma face
  cujos vértices são
  
  indice  vertice
  0       [1.,0.,0.]
  1       [0.,1.,0.]
  2       [0.,0.,1.]
"""
faces = np.array([
  [0,1,2]
])

ps_mesh = ps.register_surface_mesh("my mesh", vertices, faces)

ps.show()

<img src="./images_t1/screenshot_000001.png" alt="triangulo" width="400" height="auto">

Operando transformações simples

Sabendo que uma matriz de translação (homogênea) é dada por

$$
T(t_x, t_y, t_z) = 
\begin{bmatrix}
1 & 0 & 0 & -t_x\\
0 & 1 & 0 & -t_y\\
0 & 0 & 1 & -t_z\\
0 & 0 & 0 & 1
\end{bmatrix}
$$

Então, para mover nosso triângulo para a posição $t = [0,0,2]$, nosso ponto resultante é

$$
P' = T(t_x, t_y, t_z)P = 
\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & -2\\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 \\
0 & 0 & 0 & 1
\end{bmatrix}^T
$$


Esperamos a matriz resultante (homogenea) ser igual a

$$
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
-2 & -2 & -1 & 0 \\
1 & 1 & 1 & 1 \\
\end{bmatrix}
$$

In [4]:
ps.reset_camera_to_home_view()

# Definindo os vertices em coordenadas homogeneas
vertices_homog = np.array([
  [*vertices[0], 1],
  [*vertices[1], 1],
  [*vertices[2], 1],
  [0,0,0, 1]
]).transpose()

# Definindo matriz de translação
T = np.array([
  [1,0,0,0],
  [0,1,0,0],
  [0,0,1,-2],
  [0,0,0,1]
])

# Multiplicando matrizes
novos_vertices = np.matmul(T, vertices_homog)

# Eliminando as coordenadas homogêneas para representação
novos_vertices = np.array([
  [*novos_vertices[0][:-1]],
  [*novos_vertices[1][:-1]],
  [*novos_vertices[2][:-1]]
])

print(novos_vertices)

ps_mesh = ps.register_surface_mesh("my mesh", novos_vertices, faces)

ps.show()

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-2. -2. -1.]]


<img src="./images_t1/screenshot_000003.png" alt="triangulo" width="400" height="auto">

Como movemos apenas a coordenada z, a face foi alterada para que a nova face corresponda a um triangulo diferente

In [5]:
# Agora fixando uma posição da câmera

ps.set_navigation_style("free")

# Vetor de view_up definido na direção de z
ps.set_up_dir("z_up")

ps.init()

"""
Nesse caso, significa que estamos fixando a camera na 
posição [0,0,1]

E a mesma está olhando para a direção do alvo em [0,1,1]
"""
ps.look_at(camera_location=(0,0,1), target=(0,1,1))

# Definindo um retangulo de modo que
#   a câmera olhe para seu centro
vertices = np.array([
  [1,4,0],
  [-1,4,0],
  [1,4,1],
  [-1,4,1]
])

faces = np.array([
  [0,1,2],
  [1,3,2]
])

ps_mesh = ps.register_surface_mesh("my mesh", vertices, faces)

ps.show()

<img src="./images_t1/screenshot_000004.png" alt="triangulo" width="400" height="auto">

In [6]:
# Se alterarmos os indices das faces, o trio de vertices que
#   compõe cada uma não forma um retangulo

faces = np.array([
  [0,1,2],
  [0,1,3]
])

ps_mesh = ps.register_surface_mesh("my mesh", vertices, faces)

ps.show()

<img src="./images_t1/screenshot_000005.png" alt="triangulo" width="400" height="auto">

#### Aplicando escala

Sabemos que a matriz de escala (homogênea) é dada por
$$
S(s_x,s_y) = 
\begin{bmatrix}
s_x & 0 & 1 \\
0 & s_y & 1 \\
0 & 0 & 1 \\
\end{bmatrix}
$$

Aplicando a transformação sobre os vértices $v1 = [1,4,0]$, $v2 = [-1,4,0]$, $v3 = [1,4,1]$, $v4[-1,4,1]$

$$
P' = SP =
\begin{bmatrix}
s_x & 0 & 0 \\
0 & s_y & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
1 & 4 & 0 \\
-1 & 4 & 0 \\
1 & 4 & 1 \\
-1 & 4 & 1
\end{bmatrix}^T
$$

Para $s_x = s_y = 2$ esperamos o resultado de $P'$ ser igual a

$$
P' = \begin{bmatrix}
2 & -2 & 2 & -2 \\
8 & 8 & 8 & 8 \\
0 & 0 & 1 & 1
\end{bmatrix}
$$

In [7]:
# Aplicando escala (sem reajustar sua posição)
#  vamos dobrar o tamanho

ps.set_navigation_style("free")
ps.set_up_dir("z_up")
ps.look_at(camera_location=(0,0,1), target=(0,1,1))

sx = 2
sy = 2
S = np.array([
  [sx, 0, 0],
  [0, sy, 0],
  [0, 0, 1],
])

vertices = np.array([
  [1,4,0],
  [-1,4,0],
  [1,4,1],
  [-1,4,1]
]).transpose()

# Multiplicando matrizes
novos_vertices = np.matmul(S, vertices).transpose()

print(novos_vertices)

# Definindo um retangulo de modo que
#   a câmera olhe para seu centro

faces = np.array([
  [0,1,2],
  [0,1,3]
])

ps_mesh = ps.register_surface_mesh("my mesh", novos_vertices, faces)

ps.show()

[[ 2  8  0]
 [-2  8  0]
 [ 2  8  1]
 [-2  8  1]]


<img src="./images_t1/screenshot_000006.png" alt="triangulo" width="400" height="auto">

Como estamos em $x = 0$ e não escalamos $s_z$, a única escala ocorre em $y$

#### Aplicando rotação

Sabendo que a rotação em torno do eixo $y$ é dada por

$$
R_y(\theta) = 
\begin{bmatrix}
\cos \theta & -\sin \theta & 0 \\
0 & 1 & 0 \\
\sin \theta & \cos \theta & 1 \\
\end{bmatrix}
$$

Aplicando aos pontos do retângulo uma rotação de 45º ($= \pi / 4$), $\cos(\pi/4) = \sin(\pi/4) \approx 0.707$

$$
P' = R(\theta)P =
\begin{bmatrix}
0.707 & 0 & -0.707 \\
0 & 1 & 0 \\
0.707 & 0 & 0.707 \\
\end{bmatrix}
\begin{bmatrix}
1 & 4 & 0 \\
-1 & 4 & 0 \\
1 & 4 & 1 \\
-1 & 4 & 1
\end{bmatrix}^T
$$

In [8]:
ps.set_navigation_style("free")
ps.set_up_dir("z_up")
ps.init()
ps.look_at(camera_location=(0,0,1), target=(0,1,1))

R = np.array([
  [0.707, 0, -0.707],
  [0, 1, 0],
  [0.707, 0, 0.707],
])

vertices = np.array([
  [1,4,0],
  [-1,4,0],
  [1,4,1],
  [-1,4,1]
]).transpose()

# Multiplicando matrizes
novos_vertices = np.matmul(R, vertices).transpose()

print(novos_vertices)

# Definindo um retangulo de modo que
#   a câmera olhe para seu centro

faces = np.array([
  [0,1,2],
  [0,1,3]
])

ps_mesh = ps.register_surface_mesh("my mesh", novos_vertices, faces)

ps.show()

[[ 0.707  4.     0.707]
 [-0.707  4.    -0.707]
 [ 0.     4.     1.414]
 [-1.414  4.     0.   ]]


Porém rotacionamos em torno do eixo $y = 0$, mas estamos olhando ao longo do eixo $y = 1$

<img src="./images_t1/screenshot_000009.png" alt="triangulo" width="400" height="auto">

#### Compondo transformações

Vamos fazer apenas a rotação ao longo do eixo de visualização para o caso anterior

Precisamos da seguinte composição

1. transladar objeto para o eixo $y$: ponto $(0,1,0)$
2. rotacionar em $\pi/4$
3. transladar objeto de volta para $y = (0,1,1)$

In [10]:
ps.set_navigation_style("free")
ps.set_up_dir("z_up")
ps.look_at(camera_location=(0,0,1), target=(0,1,1))

T_volta = np.array([
  [1,0,0,0],
  [0,1,0,-1],
  [0,0,1,-1],
  [0,0,0,1],
])

RT = np.array([
  [0.707, 0, -0.707, 0],
  [0, 1, 0, -1],
  [0.707, 1, 0.707, 0],
  [0,0,0,1]
])


vertices = np.array([
  [1,4,0,1],
  [-1,4,0,1],
  [1,4,1,1],
  [-1,4,1,1]
]).transpose()

# novos_vertices = np.matmul(T_volta, vertices).transpose()

# Multiplicando matrizes
novos_vertices = np.matmul(T_volta, np.matmul(RT, vertices)).transpose()

# Eliminando as coordenadas homogêneas para representação
novos_vertices = np.array([
  [*novos_vertices[0][:-1]],
  [*novos_vertices[1][:-1]],
  [*novos_vertices[2][:-1]],
  [*novos_vertices[3][:-1]]
])
print(novos_vertices)

# Definindo um retangulo de modo que
#   a câmera olhe para seu centro

faces = np.array([
  [0,1,2],
  [0,1,3]
])

ps_mesh = ps.register_surface_mesh("my mesh", novos_vertices, faces)

ps.show()


[[ 0.707  2.     3.707]
 [-0.707  2.     2.293]
 [ 0.     2.     4.414]
 [-1.414  2.     3.   ]]


<img src="./images_t1/screenshot_000010.png" alt="triangulo" width="400" height="auto">

### Entendendo animações

In [5]:
def animar_rotacao_y(vertices, angulo):
  R = np.array([
    [np.cos(angulo), 0, -np.sin(angulo)],
    [0, 1, 0],
    [np.sin(angulo), 0, -np.cos(angulo)],
  ])
  resultado = np.matmul(R, vertices.transpose()).transpose()
  return resultado

In [6]:
def animar_rotacao_y(vertices, angulo):
  R = np.array([
    [np.cos(angulo), 0, -np.sin(angulo)],
    [0, 1, 0],
    [np.sin(angulo), 0, np.cos(angulo)],
  ])
  resultado = np.matmul(R, vertices.transpose()).transpose()
  return resultado

In [7]:
ps.set_navigation_style("free")
ps.set_up_dir("z_up")

ps.look_at(camera_location=(0,0,1), target=(0,1,1))

def process(vertices, dt):
  angulo = dt
  vertices = animar_rotacao_y(vertices, angulo)
  return vertices


def main():
  vertices_original = np.array([
    [1,4,0],
    [-1,4,0],
    [1,4,1],
    [-1,4,1]
  ])

  faces = np.array([
    [0,1,2],
    [1,3,2]
  ])

  ps_mesh = ps.register_surface_mesh("my mesh", vertices_original, faces)
  dt = 0
  def callback():
    
    nonlocal vertices_original, dt
    vertices = process(vertices_original, dt)
    dt +=  0.01

    ps_mesh.update_vertex_positions(vertices)

  ps.set_user_callback(callback)
  ps.show()
main()

Animação de rotação ao longo do eixo (0,1,0). Camera em (0,0,1) olhando para (0,1,1)

[RETANGULO - GIF](images_t1/video1466083960.gif)


### Importando malhas: arquivos .obj

In [14]:
def verticesFacesObj(arquivo_obj):
  vertices = []
  faces = []
  with open(arquivo_obj, 'r') as dados:
    for linha in dados.readlines():
      linha = linha.split()
      if len(linha) == 0: continue
      if linha[0] == 'v':
        v = [float(i) for i in linha[1:]]
        vertices.append(v)
      elif linha[0] == 'f':
        f = [int(i)-1 for i in linha[1:]]
        faces.append(f)
  return {'vertices': np.array(vertices), 'faces': np.array(faces)}

In [9]:
# CUBO arquivo .obj

obj = verticesFacesObj('./objFiles/cube.obj')
vertices = obj['vertices']
faces = obj['faces']
print('Vertices:\n', vertices)
print('Faces:\n', faces)

Vertices:
 [[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [-0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5]]
Faces:
 [[0 1 3]
 [0 3 2]
 [2 3 5]
 [2 5 4]
 [4 5 7]
 [4 7 6]
 [6 7 1]
 [6 1 0]
 [1 7 5]
 [1 5 3]
 [6 0 2]
 [6 2 4]]


In [20]:
ps.set_navigation_style("free")
ps.set_up_dir("z_up")
ps.look_at(camera_location=(0,-5,1), target=(0,1,1))

def process(vertices, dt):
  angulo = dt
  vertices = animar_rotacao_y(vertices, angulo)
  return vertices


def main(V, F):
  ps_mesh = ps.register_surface_mesh("my mesh", V, F)
  dt = 0
  def callback():
    
    nonlocal V, dt
    vertices = process(V, dt)
    dt +=  0.03

    ps_mesh.update_vertex_positions(vertices)

  ps.set_user_callback(callback)
  ps.show()

ps.register_point_cloud("my points", np.array([[0,0,1],[0,0,-2]]))
obj = verticesFacesObj('./objFiles/cube.obj')
vertices = obj['vertices']
faces = obj['faces']
main(vertices, faces)

Animação de rotação ao longo do eixo (0,1,0)

[CUBO - GIF](images_t1/video1892852990.gif)

In [32]:
ps.set_navigation_style("free")
ps.set_up_dir("z_up")
ps.look_at(camera_location=(-300,200,200), target=(0,1,1))

ps.register_point_cloud("my points", np.array([[0,-100,0], [0,100,0],[-100, -100,-200]]))
obj = verticesFacesObj('./objFiles/teapot.obj')
vertices = obj['vertices']
faces = obj['faces']
main(vertices, faces)

Animação de rotação ao longo do eixo (0,1,0) - TEAPOT!

[TEAPOT - GIF](images_t1/video1104591166.gif)

#### ESPECIFICAÇÕES - TRABALHO 1